/*
 * ICON BLOCK
 */
#define APP_ICON        1001

/*
 * VERSION BLOCK
 */
#define FILE_VERSION    L"@FILE_VERSION_MAJOR@.@FILE_VERSION_MINOR@.@FILE_VERSION_PATCH@.@VERSION_BUILD@"
#define PRODUCT_VERSION L"@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@.@VERSION_BUILD@"