name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./azure-build.ps1
        
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
    
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: knox-${{secrets.BUILD_VERSION}}-b${{github.run_number}}-${{steps.time.outputs.time}}.zip
        path: ${{github.workspace}}/out
        directory: ${{github.workspace}}/out/artifacts
        # exclusions: 
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{secrets.BUILD_VERSION}}-b${{github.run_number}}-${{steps.time.outputs.time}}
        path: ${{github.workspace}}/out/artifacts/knox-*.zip
        if-no-files-found: error
        retention-days: 90

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}